config/routes.rb
Rails.application.routes.draw do
  devise_for :passengers, controllers: {
    registrations: 'passengers/registrations',
    sessions: 'passengers/sessions'
  }
  devise_scope :passenger do
    get '/passengers/confirm_otp/:id', to: 'passengers/registrations#confirm_otp', as: :confirm_otp
    post '/passengers/verify_otp/:id', to: 'passengers/registrations#verify_otp', as: :verify_otp
  end
  resources :vehicles
  resources :passengers, only: [:update]
  get '/rides/ride_confirmation', to: 'rides#ride_confirmation'
  resources :rides do
    get :locations, on: :collection
  end
  resources :drivers
  root "rides#index"
  get '/rides/locations', to: 'rides#locations'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/driver.rb
class Driver < ApplicationRecord
  belongs_to :passenger
  has_many :vehicles
  has_many :rides
  has_many :passengers, through: :rides
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  # Add any other fields you need
  validates_uniqueness_of :email, if: -> { email.present? }
  before_validation :strip_whitespace
  attr_accessor :otp
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
  has_one :driver
  has_many :rides
  has_many :drivers, through: :rides

  private

  def strip_whitespace
    self.email = email.strip if email.present?
  end
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :passenger
  belongs_to :driver, optional: true
  validates :location_from, :location_to, :date_time_when, presence: true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :driver
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:otp_attempt])
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
  end

  def show
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/locations_controller.rb
# app/controllers/locations_controller.rb

class LocationsController < ApplicationController
  def autocomplete
    @locations = Location.where('name ILIKE ?', "%#{params[:q]}%") # Adjust the query as needed
    respond_to do |format|
      format.json { render json: @locations.to_json }
    end
  end
end

app/controllers/passengers/registrations_controller.rb
# app/controllers/passengers/registrations_controller.rb

class Passengers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  def new
    super
  end

  def create
    build_resource(sign_up_params)

    if resource.valid?(:validate_email_and_mobile)
      # Generate a 4-digit OTP
      resource.otp = rand(1000..9999).to_s

      if resource.save(validate: false)
        # Send OTP to passenger's email (replace this with your actual OTP sending logic)
        resource.update(verification_code: resource.otp)
        send_otp(resource)
        
        # Redirect to a page to confirm OTP
        redirect_to confirm_otp_path(resource)
        return
      end
    end

    clean_up_passwords resource
    set_minimum_password_length
    respond_with resource
  end

  def confirm_otp
    @passenger = resource_class.find(params[:id])
  end

  def verify_otp
    @passenger = Passenger.find(params[:id])
    if @passenger.verification_code == params[:otp]
      # OTP verified, continue with the registration process
      if @passenger.update(sign_up_params)
        sign_in(@passenger) # Automatically sign in the passenger after registration
        redirect_to root_path # Redirect to the desired path after successful registration
      else
        @passenger.errors.add(:otp, "SOmething wrong OTP")
        render :confirm_otp
      end
    else
      @passenger.errors.add(:otp, "Invalid OTP")
      render :confirm_otp
    end
  end

  private

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :contact_no])
  end

  def send_otp(passenger)
    # Implement your OTP sending logic here (e.g., send an email)
    # For simplicity, let's just print it to the console
    puts "OTP for #{passenger.email}: #{passenger.otp}"
  end
end

app/controllers/passengers/sessions_controller.rb
# app/controllers/passengers/sessions_controller.rb

class Passengers::SessionsController < Devise::SessionsController
  def create
    super
  end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :find_passenger, only: [:show, :update, :destroy]
  def index
    passengers = Passenger.all
  end

  def show
  end

  def new
    @passenger = Passenger.new
  end

  def create
    @passenger = Passenger.new(passenger_params)

    if @passenger.save
      redirect_to passengers_path
    else
      redirect_to new_passengers_path
    end
  end

  def update
  end

  def destroy
  end

  private

  def find_passenger
    @passenger = Passenger.find_by(id: params[:id])
  end

  def passenger_params
  params.require(:passenger).permit(:first_name, :last_name, :email, :contact_no)
end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :find_ride , only: [:show, :update, :destroy]
  def index
    @rides = Ride.all
  end

  def show
  end

  def new
    @ride = Ride.new
  end

  def create
    @ride = Ride.new(ride_params)
    @ride.passenger_id = current_passenger.id
    if @ride.save
      #  available_driver = Driver.find_available_driver
      # @ride.update(driver: available_driver) if available_driver.present?
      redirect_to rides_path,  notice: 'Ride was successfully created.'
    else
      puts "#{@ride.errors.full_messages}"
      redirect_to new_ride_path
    end
  end

  def ride_confirmation
    respond_to do |format|
      format.html { render 'ride_confirmation' } # Assuming 'ride_confirmation' is the name of your HTML template
    end
  end

  def update
  end

  def destroy
  end
  
  def locations
    query = params[:q]
    # Implement logic to fetch locations based on the query (e.g., from a hardcoded list or external service)
    locations = Location.where('name LIKE ?', "%#{query}%").pluck(:name)
    render json: locations
  end
  
  private
  
  def find_ride
    @ride =Ride.find_by(id: params[:id])
  end

  def ride_params
    params.require(:ride).permit(:location_from, :location_to, :date_time_when, :offer_fare, :confirmation_code)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
  end

  def show
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/drivers/create.html.haml
%h1 Drivers#create
%p Find me in app/views/drivers/create.html.erb

app/views/drivers/destroy.html.haml
%h1 Drivers#destroy
%p Find me in app/views/drivers/destroy.html.erb

app/views/drivers/index.html.haml
%h1 Drivers#index
%p Find me in app/views/drivers/index.html.erb

app/views/drivers/show.html.haml
%h1 Drivers#show
%p Find me in app/views/drivers/show.html.erb

app/views/drivers/update.html.haml
%h1 Drivers#update
%p Find me in app/views/drivers/update.html.erb

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Indrive
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %link{:crossorigin => "anonymous", :href => "https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css", :integrity => "sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm", :rel => "stylesheet"}/

    %script{:crossorigin => "anonymous", :integrity => "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN", :src => "https://code.jquery.com/jquery-3.2.1.slim.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q", :src => "https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl", :src => "https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"}

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/passengers/destroy.html.haml
%h1 Passengers#destroy
%p Find me in app/views/passengers/destroy.html.erb

app/views/passengers/index.html.haml
%h1 Passengers#index
%p Find me in app/views/passengers/index.html.erb

app/views/passengers/new.html.erb
<h1>Passengers#create</h1>
<p>Find me in app/views/passengers/create.html.erb</p>
<%= form_for @passenger do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :contact_no %>
  <%= f.text_field :contact_no %>

  <%= f.submit %>
<% end %>

app/views/passengers/new.html.haml
%h1 Passengers#create
%p Find me in app/views/passengers/create.html.erb
= form_for @passenger do |f|
  = f.label :first_name
  = f.text_field :first_name
  = f.label :last_name
  = f.text_field :last_name
  = f.label :email
  = f.text_field :email
  = f.label :contact_no
  = f.text_field :contact_no
  = f.submit

app/views/passengers/show.html.haml
%h1 Passengers#show
%p Find me in app/views/passengers/show.html.erb

app/views/passengers/update.html.haml
%h1 Passengers#update
%p Find me in app/views/passengers/update.html.erb

app/views/rides/destroy.html.haml
%h1 Rides#destroy
%p Find me in app/views/rides/destroy.html.erb

app/views/rides/index.html.haml
%h1 Rides#index
%p Find me in app/views/rides/index.html.erb
- if passenger_signed_in?
  = button_to 'Sign Out', destroy_passenger_session_path, method: :delete ,data: { turbo_method: :delete }
  = link_to 'New Ride', new_ride_path
- else 
  = link_to 'Sign In', new_passenger_session_path
  = link_to 'Sign Up', new_passenger_registration_path

app/views/rides/new.html.haml
%h1 Rides#create
%p Find me in app/views/rides/create.html.erb

= form_for @ride , id: 'ride-form' do |f|
  = f.label :location_from
  = f.text_field :location_from, required: true, list: 'locations-datalist', class: 'location-autocomplete'  
  = f.label :location_to
  = f.text_field :location_to, required: true
  = f.label :date_time_when
  = f.datetime_field :date_time_when, required: true
  = f.label :offer_fare
  = f.text_field :offer_fare
  - f.submit
%button.btn.btn-primary{"data-target" => "#exampleModal", "data-toggle" => "modal", :type => "button"}
  Next

#exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Confirm Ride
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        \...
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
        %button.btn.btn-primary{:type => "button", id: "confirmButton"} Confirm



:javascript
  $(document).ready(function() {
    // Handle Next button click
    $('#nextButton').click(function() {
      // Validate form here if needed
      // For example, you can check if required fields are filled

      // Open the modal
      $('#exampleModal').modal('show');
    });

    // Handle Confirm button click
    $('#confirmButton').click(function() {
      // Submit the form
      $('#new_ride').submit();

      // Close the modal
      $('#exampleModal').modal('hide');
    });
  });

app/views/rides/ride_confirmation.html.haml
%h1 confirmation page

app/views/rides/show.html.erb
<h1>Rides#show</h1>
<p>Find me in app/views/rides/show.html.erb</p>

app/views/rides/show.html.haml
<h1>Rides#show</h1>
<p>Find me in app/views/rides/show.html.erb</p>

app/views/rides/update.html.haml
%h1 Rides#update
%p Find me in app/views/rides/update.html.erb

app/views/vehicles/create.html.haml
%h1 Vehicles#create
%p Find me in app/views/vehicles/create.html.erb

app/views/vehicles/destroy.html.haml
%h1 Vehicles#destroy
%p Find me in app/views/vehicles/destroy.html.erb

app/views/vehicles/index.html.haml
%h1 Vehicles#index
%p Find me in app/views/vehicles/index.html.erb

app/views/vehicles/show.html.haml
%h1 Vehicles#show
%p Find me in app/views/vehicles/show.html.erb

app/views/vehicles/update.html.haml
%h1 Vehicles#update
%p Find me in app/views/vehicles/update.html.erb